/* ═══ Cotations Fret — données FICTIVES (prototype) ═══ */

const ZONES = {
  maghreb: 'Maghreb',
  afrique_ouest: "Afrique de l'Ouest",
  europe: 'Europe',
  monde: 'Monde entier',
};

const TRANSPORTEURS = [
  { id: 'translog',  nom: 'Translog Med',        contact: 'Karim',    email: 'k.bensaid@translogmed.example',   zones: ['maghreb'],                 couleur: '#e01414' },
  { id: 'atlas',     nom: 'Atlas Freight',       contact: 'Sofia',    email: 'sofia@atlasfreight.example',      zones: ['maghreb'],                 couleur: '#b7791f' },
  { id: 'seafret',   nom: 'Seafret Atlantique',  contact: 'Marc',     email: 'm.leroy@seafret.example',         zones: ['maghreb', 'afrique_ouest'], couleur: '#0a7d33' },
  { id: 'capouest',  nom: 'CapOuest Shipping',   contact: 'Awa',      email: 'awa@capouest.example',            zones: ['afrique_ouest'],           couleur: '#7c3aed' },
  { id: 'bernardi',  nom: 'Groupe Bernardi',     contact: 'Luca',     email: 'l.bernardi@bernardi.example',     zones: ['europe'],                  couleur: '#0369a1' },
  { id: 'eurocargo', nom: 'EuroCargo Express',   contact: 'Petra',    email: 'petra@eurocargo.example',         zones: ['europe'],                  couleur: '#be185d' },
  { id: 'mtl',       nom: 'MTL Overseas',        contact: 'David',    email: 'd.cohen@mtloverseas.example',     zones: ['monde'],                   couleur: '#334155' },
  { id: 'globalwave',nom: 'Global Wave Logistics', contact: 'Yusuf',  email: 'yusuf@globalwave.example',        zones: ['monde'],                   couleur: '#ea580c' },
];

const PAYS = [
  { code: 'MA', nom: 'Maroc',          flag: '🇲🇦', zone: 'maghreb',        port: 'Casablanca' },
  { code: 'DZ', nom: 'Algérie',        flag: '🇩🇿', zone: 'maghreb',        port: 'Alger' },
  { code: 'TN', nom: 'Tunisie',        flag: '🇹🇳', zone: 'maghreb',        port: 'Radès' },
  { code: 'SN', nom: 'Sénégal',        flag: '🇸🇳', zone: 'afrique_ouest',  port: 'Dakar' },
  { code: 'CI', nom: "Côte d'Ivoire",  flag: '🇨🇮', zone: 'afrique_ouest',  port: 'Abidjan' },
  { code: 'GH', nom: 'Ghana',          flag: '🇬🇭', zone: 'afrique_ouest',  port: 'Tema' },
  { code: 'NG', nom: 'Nigeria',        flag: '🇳🇬', zone: 'afrique_ouest',  port: 'Lagos (Apapa)' },
  { code: 'CM', nom: 'Cameroun',       flag: '🇨🇲', zone: 'afrique_ouest',  port: 'Douala' },
  { code: 'GN', nom: 'Guinée',         flag: '🇬🇳', zone: 'afrique_ouest',  port: 'Conakry' },
  { code: 'TG', nom: 'Togo',           flag: '🇹🇬', zone: 'afrique_ouest',  port: 'Lomé' },
  { code: 'ES', nom: 'Espagne',        flag: '🇪🇸', zone: 'europe',         port: 'Valence' },
  { code: 'PT', nom: 'Portugal',       flag: '🇵🇹', zone: 'europe',         port: 'Leixões' },
  { code: 'IT', nom: 'Italie',         flag: '🇮🇹', zone: 'europe',         port: 'Gênes' },
  { code: 'DE', nom: 'Allemagne',      flag: '🇩🇪', zone: 'europe',         port: 'Hambourg' },
  { code: 'PL', nom: 'Pologne',        flag: '🇵🇱', zone: 'europe',         port: 'Gdańsk' },
  { code: 'RO', nom: 'Roumanie',       flag: '🇷🇴', zone: 'europe',         port: 'Constanța' },
  { code: 'GR', nom: 'Grèce',          flag: '🇬🇷', zone: 'europe',         port: 'Le Pirée' },
  { code: 'TR', nom: 'Turquie',        flag: '🇹🇷', zone: 'monde',          port: 'Istanbul (Ambarlı)' },
  { code: 'EG', nom: 'Égypte',         flag: '🇪🇬', zone: 'monde',          port: 'Alexandrie' },
  { code: 'LB', nom: 'Liban',          flag: '🇱🇧', zone: 'monde',          port: 'Beyrouth' },
  { code: 'AE', nom: 'Émirats',        flag: '🇦🇪', zone: 'monde',          port: 'Jebel Ali' },
  { code: 'IN', nom: 'Inde',           flag: '🇮🇳', zone: 'monde',          port: 'Nhava Sheva' },
];

/* prix de référence fictifs par pays (€ / container 20') pour la simulation */
const PRIX_BASE = {
  MA: 880, DZ: 1010, TN: 940, SN: 1420, CI: 1510, GH: 1580, NG: 1720, CM: 1650,
  GN: 1560, TG: 1540, ES: 620, PT: 680, IT: 710, DE: 760, PL: 830, RO: 950,
  GR: 900, TR: 1050, EG: 1150, LB: 1250, AE: 1500, IN: 1650,
};

/* pays de provenance possibles (Europe papetière, France par défaut) */
const PAYS_PROV = [
  { code: 'FR', nom: 'France', flag: '🇫🇷' },
  { code: 'BE', nom: 'Belgique', flag: '🇧🇪' },
  { code: 'NL', nom: 'Pays-Bas', flag: '🇳🇱' },
  { code: 'DE', nom: 'Allemagne', flag: '🇩🇪' },
  { code: 'ES', nom: 'Espagne', flag: '🇪🇸' },
  { code: 'PT', nom: 'Portugal', flag: '🇵🇹' },
  { code: 'IT', nom: 'Italie', flag: '🇮🇹' },
  { code: 'PL', nom: 'Pologne', flag: '🇵🇱' },
  { code: 'GB', nom: 'Royaume-Uni', flag: '🇬🇧' },
  { code: 'SE', nom: 'Suède', flag: '🇸🇪' },
  { code: 'FI', nom: 'Finlande', flag: '🇫🇮' },
  { code: 'NO', nom: 'Norvège', flag: '🇳🇴' },
  { code: 'DK', nom: 'Danemark', flag: '🇩🇰' },
  { code: 'IE', nom: 'Irlande', flag: '🇮🇪' },
  { code: 'GR', nom: 'Grèce', flag: '🇬🇷' },
  { code: 'TR', nom: 'Turquie', flag: '🇹🇷' },
  { code: 'RO', nom: 'Roumanie', flag: '🇷🇴' },
  { code: 'BG', nom: 'Bulgarie', flag: '🇧🇬' },
  { code: 'HR', nom: 'Croatie', flag: '🇭🇷' },
  { code: 'SI', nom: 'Slovénie', flag: '🇸🇮' },
  { code: 'LV', nom: 'Lettonie', flag: '🇱🇻' },
  { code: 'LT', nom: 'Lituanie', flag: '🇱🇹' },
  { code: 'EE', nom: 'Estonie', flag: '🇪🇪' },
  { code: 'AT', nom: 'Autriche', flag: '🇦🇹' },
  { code: 'CH', nom: 'Suisse', flag: '🇨🇭' },
  { code: 'CZ', nom: 'Tchéquie', flag: '🇨🇿' },
  { code: 'HU', nom: 'Hongrie', flag: '🇭🇺' },
  /* — tous les autres pays (alphabétique) — */
  { code: 'AF', nom: 'Afghanistan', flag: '🇦🇫' },
  { code: 'ZA', nom: 'Afrique du Sud', flag: '🇿🇦' },
  { code: 'AL', nom: 'Albanie', flag: '🇦🇱' },
  { code: 'DZ', nom: 'Algérie', flag: '🇩🇿' },
  { code: 'AD', nom: 'Andorre', flag: '🇦🇩' },
  { code: 'AO', nom: 'Angola', flag: '🇦🇴' },
  { code: 'SA', nom: 'Arabie saoudite', flag: '🇸🇦' },
  { code: 'AR', nom: 'Argentine', flag: '🇦🇷' },
  { code: 'AM', nom: 'Arménie', flag: '🇦🇲' },
  { code: 'AU', nom: 'Australie', flag: '🇦🇺' },
  { code: 'AZ', nom: 'Azerbaïdjan', flag: '🇦🇿' },
  { code: 'BS', nom: 'Bahamas', flag: '🇧🇸' },
  { code: 'BH', nom: 'Bahreïn', flag: '🇧🇭' },
  { code: 'BD', nom: 'Bangladesh', flag: '🇧🇩' },
  { code: 'MM', nom: 'Birmanie', flag: '🇲🇲' },
  { code: 'BY', nom: 'Biélorussie', flag: '🇧🇾' },
  { code: 'BO', nom: 'Bolivie', flag: '🇧🇴' },
  { code: 'BA', nom: 'Bosnie-Herzégovine', flag: '🇧🇦' },
  { code: 'BW', nom: 'Botswana', flag: '🇧🇼' },
  { code: 'BN', nom: 'Brunei', flag: '🇧🇳' },
  { code: 'BR', nom: 'Brésil', flag: '🇧🇷' },
  { code: 'BF', nom: 'Burkina Faso', flag: '🇧🇫' },
  { code: 'BI', nom: 'Burundi', flag: '🇧🇮' },
  { code: 'BZ', nom: 'Bélize', flag: '🇧🇿' },
  { code: 'BJ', nom: 'Bénin', flag: '🇧🇯' },
  { code: 'KH', nom: 'Cambodge', flag: '🇰🇭' },
  { code: 'CM', nom: 'Cameroun', flag: '🇨🇲' },
  { code: 'CA', nom: 'Canada', flag: '🇨🇦' },
  { code: 'CV', nom: 'Cap-Vert', flag: '🇨🇻' },
  { code: 'CF', nom: 'Centrafrique', flag: '🇨🇫' },
  { code: 'CL', nom: 'Chili', flag: '🇨🇱' },
  { code: 'CN', nom: 'Chine', flag: '🇨🇳' },
  { code: 'CY', nom: 'Chypre', flag: '🇨🇾' },
  { code: 'CO', nom: 'Colombie', flag: '🇨🇴' },
  { code: 'KM', nom: 'Comores', flag: '🇰🇲' },
  { code: 'CG', nom: 'Congo', flag: '🇨🇬' },
  { code: 'KR', nom: 'Corée du Sud', flag: '🇰🇷' },
  { code: 'CR', nom: 'Costa Rica', flag: '🇨🇷' },
  { code: 'CU', nom: 'Cuba', flag: '🇨🇺' },
  { code: 'CI', nom: "Côte d'Ivoire", flag: '🇨🇮' },
  { code: 'DJ', nom: 'Djibouti', flag: '🇩🇯' },
  { code: 'SZ', nom: 'Eswatini', flag: '🇸🇿' },
  { code: 'GA', nom: 'Gabon', flag: '🇬🇦' },
  { code: 'GM', nom: 'Gambie', flag: '🇬🇲' },
  { code: 'GH', nom: 'Ghana', flag: '🇬🇭' },
  { code: 'GT', nom: 'Guatemala', flag: '🇬🇹' },
  { code: 'GN', nom: 'Guinée', flag: '🇬🇳' },
  { code: 'GQ', nom: 'Guinée équatoriale', flag: '🇬🇶' },
  { code: 'GW', nom: 'Guinée-Bissau', flag: '🇬🇼' },
  { code: 'GY', nom: 'Guyana', flag: '🇬🇾' },
  { code: 'GE', nom: 'Géorgie', flag: '🇬🇪' },
  { code: 'HT', nom: 'Haïti', flag: '🇭🇹' },
  { code: 'HN', nom: 'Honduras', flag: '🇭🇳' },
  { code: 'HK', nom: 'Hong Kong', flag: '🇭🇰' },
  { code: 'IN', nom: 'Inde', flag: '🇮🇳' },
  { code: 'ID', nom: 'Indonésie', flag: '🇮🇩' },
  { code: 'IQ', nom: 'Irak', flag: '🇮🇶' },
  { code: 'IR', nom: 'Iran', flag: '🇮🇷' },
  { code: 'IS', nom: 'Islande', flag: '🇮🇸' },
  { code: 'IL', nom: 'Israël', flag: '🇮🇱' },
  { code: 'JM', nom: 'Jamaïque', flag: '🇯🇲' },
  { code: 'JP', nom: 'Japon', flag: '🇯🇵' },
  { code: 'JO', nom: 'Jordanie', flag: '🇯🇴' },
  { code: 'KZ', nom: 'Kazakhstan', flag: '🇰🇿' },
  { code: 'KE', nom: 'Kenya', flag: '🇰🇪' },
  { code: 'KG', nom: 'Kirghizistan', flag: '🇰🇬' },
  { code: 'KW', nom: 'Koweït', flag: '🇰🇼' },
  { code: 'LA', nom: 'Laos', flag: '🇱🇦' },
  { code: 'LS', nom: 'Lesotho', flag: '🇱🇸' },
  { code: 'LB', nom: 'Liban', flag: '🇱🇧' },
  { code: 'LR', nom: 'Liberia', flag: '🇱🇷' },
  { code: 'LY', nom: 'Libye', flag: '🇱🇾' },
  { code: 'LI', nom: 'Liechtenstein', flag: '🇱🇮' },
  { code: 'LU', nom: 'Luxembourg', flag: '🇱🇺' },
  { code: 'MK', nom: 'Macédoine du Nord', flag: '🇲🇰' },
  { code: 'MG', nom: 'Madagascar', flag: '🇲🇬' },
  { code: 'MY', nom: 'Malaisie', flag: '🇲🇾' },
  { code: 'MW', nom: 'Malawi', flag: '🇲🇼' },
  { code: 'MV', nom: 'Maldives', flag: '🇲🇻' },
  { code: 'ML', nom: 'Mali', flag: '🇲🇱' },
  { code: 'MT', nom: 'Malte', flag: '🇲🇹' },
  { code: 'MA', nom: 'Maroc', flag: '🇲🇦' },
  { code: 'MR', nom: 'Mauritanie', flag: '🇲🇷' },
  { code: 'MX', nom: 'Mexique', flag: '🇲🇽' },
  { code: 'MD', nom: 'Moldavie', flag: '🇲🇩' },
  { code: 'MC', nom: 'Monaco', flag: '🇲🇨' },
  { code: 'MN', nom: 'Mongolie', flag: '🇲🇳' },
  { code: 'ME', nom: 'Monténégro', flag: '🇲🇪' },
  { code: 'MZ', nom: 'Mozambique', flag: '🇲🇿' },
  { code: 'NA', nom: 'Namibie', flag: '🇳🇦' },
  { code: 'NI', nom: 'Nicaragua', flag: '🇳🇮' },
  { code: 'NE', nom: 'Niger', flag: '🇳🇪' },
  { code: 'NG', nom: 'Nigeria', flag: '🇳🇬' },
  { code: 'NZ', nom: 'Nouvelle-Zélande', flag: '🇳🇿' },
  { code: 'NP', nom: 'Népal', flag: '🇳🇵' },
  { code: 'OM', nom: 'Oman', flag: '🇴🇲' },
  { code: 'UG', nom: 'Ouganda', flag: '🇺🇬' },
  { code: 'UZ', nom: 'Ouzbékistan', flag: '🇺🇿' },
  { code: 'PK', nom: 'Pakistan', flag: '🇵🇰' },
  { code: 'PA', nom: 'Panama', flag: '🇵🇦' },
  { code: 'PG', nom: 'Papouasie-Nlle-Guinée', flag: '🇵🇬' },
  { code: 'PY', nom: 'Paraguay', flag: '🇵🇾' },
  { code: 'PH', nom: 'Philippines', flag: '🇵🇭' },
  { code: 'PE', nom: 'Pérou', flag: '🇵🇪' },
  { code: 'QA', nom: 'Qatar', flag: '🇶🇦' },
  { code: 'CD', nom: 'RD Congo', flag: '🇨🇩' },
  { code: 'RU', nom: 'Russie', flag: '🇷🇺' },
  { code: 'RW', nom: 'Rwanda', flag: '🇷🇼' },
  { code: 'DO', nom: 'Rép. dominicaine', flag: '🇩🇴' },
  { code: 'SV', nom: 'Salvador', flag: '🇸🇻' },
  { code: 'RS', nom: 'Serbie', flag: '🇷🇸' },
  { code: 'SC', nom: 'Seychelles', flag: '🇸🇨' },
  { code: 'SL', nom: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'SG', nom: 'Singapour', flag: '🇸🇬' },
  { code: 'SK', nom: 'Slovaquie', flag: '🇸🇰' },
  { code: 'SO', nom: 'Somalie', flag: '🇸🇴' },
  { code: 'SD', nom: 'Soudan', flag: '🇸🇩' },
  { code: 'SS', nom: 'Soudan du Sud', flag: '🇸🇸' },
  { code: 'LK', nom: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'SR', nom: 'Suriname', flag: '🇸🇷' },
  { code: 'SY', nom: 'Syrie', flag: '🇸🇾' },
  { code: 'SN', nom: 'Sénégal', flag: '🇸🇳' },
  { code: 'TJ', nom: 'Tadjikistan', flag: '🇹🇯' },
  { code: 'TZ', nom: 'Tanzanie', flag: '🇹🇿' },
  { code: 'TW', nom: 'Taïwan', flag: '🇹🇼' },
  { code: 'TD', nom: 'Tchad', flag: '🇹🇩' },
  { code: 'TH', nom: 'Thaïlande', flag: '🇹🇭' },
  { code: 'TG', nom: 'Togo', flag: '🇹🇬' },
  { code: 'TT', nom: 'Trinité-et-Tobago', flag: '🇹🇹' },
  { code: 'TN', nom: 'Tunisie', flag: '🇹🇳' },
  { code: 'TM', nom: 'Turkménistan', flag: '🇹🇲' },
  { code: 'UA', nom: 'Ukraine', flag: '🇺🇦' },
  { code: 'UY', nom: 'Uruguay', flag: '🇺🇾' },
  { code: 'VE', nom: 'Venezuela', flag: '🇻🇪' },
  { code: 'VN', nom: 'Vietnam', flag: '🇻🇳' },
  { code: 'YE', nom: 'Yémen', flag: '🇾🇪' },
  { code: 'ZM', nom: 'Zambie', flag: '🇿🇲' },
  { code: 'ZW', nom: 'Zimbabwe', flag: '🇿🇼' },
  { code: 'EG', nom: 'Égypte', flag: '🇪🇬' },
  { code: 'AE', nom: 'Émirats arabes unis', flag: '🇦🇪' },
  { code: 'EC', nom: 'Équateur', flag: '🇪🇨' },
  { code: 'ER', nom: 'Érythrée', flag: '🇪🇷' },
  { code: 'US', nom: 'États-Unis', flag: '🇺🇸' },
  { code: 'ET', nom: 'Éthiopie', flag: '🇪🇹' },
  { code: 'MU', nom: 'Île Maurice', flag: '🇲🇺' },
];

/* port(s) PHARE(S) de chaque pays maritime — les plus gros d'abord */
const PORTS_PROV = [
  { code: 'p_fr0', nom: 'Le Havre', pays: 'France', flag: '🇫🇷' },
  { code: 'p_fr1', nom: 'Marseille (Fos)', pays: 'France', flag: '🇫🇷' },
  { code: 'p_fr2', nom: 'Dunkerque', pays: 'France', flag: '🇫🇷' },
  { code: 'p_fr3', nom: 'Rouen', pays: 'France', flag: '🇫🇷' },
  { code: 'p_be0', nom: 'Anvers', pays: 'Belgique', flag: '🇧🇪' },
  { code: 'p_be1', nom: 'Zeebrugge', pays: 'Belgique', flag: '🇧🇪' },
  { code: 'p_nl0', nom: 'Rotterdam', pays: 'Pays-Bas', flag: '🇳🇱' },
  { code: 'p_nl1', nom: 'Amsterdam', pays: 'Pays-Bas', flag: '🇳🇱' },
  { code: 'p_de0', nom: 'Hambourg', pays: 'Allemagne', flag: '🇩🇪' },
  { code: 'p_de1', nom: 'Bremerhaven', pays: 'Allemagne', flag: '🇩🇪' },
  { code: 'p_es0', nom: 'Valence', pays: 'Espagne', flag: '🇪🇸' },
  { code: 'p_es1', nom: 'Algésiras', pays: 'Espagne', flag: '🇪🇸' },
  { code: 'p_es2', nom: 'Barcelone', pays: 'Espagne', flag: '🇪🇸' },
  { code: 'p_es3', nom: 'Bilbao', pays: 'Espagne', flag: '🇪🇸' },
  { code: 'p_pt0', nom: 'Lisbonne', pays: 'Portugal', flag: '🇵🇹' },
  { code: 'p_pt1', nom: 'Leixões (Porto)', pays: 'Portugal', flag: '🇵🇹' },
  { code: 'p_pt2', nom: 'Sines', pays: 'Portugal', flag: '🇵🇹' },
  { code: 'p_it0', nom: 'Gênes', pays: 'Italie', flag: '🇮🇹' },
  { code: 'p_it1', nom: 'La Spezia', pays: 'Italie', flag: '🇮🇹' },
  { code: 'p_it2', nom: 'Livourne', pays: 'Italie', flag: '🇮🇹' },
  { code: 'p_pl0', nom: 'Gdansk', pays: 'Pologne', flag: '🇵🇱' },
  { code: 'p_pl1', nom: 'Gdynia', pays: 'Pologne', flag: '🇵🇱' },
  { code: 'p_gb0', nom: 'Felixstowe', pays: 'Royaume-Uni', flag: '🇬🇧' },
  { code: 'p_gb1', nom: 'Southampton', pays: 'Royaume-Uni', flag: '🇬🇧' },
  { code: 'p_gb2', nom: 'London Gateway', pays: 'Royaume-Uni', flag: '🇬🇧' },
  { code: 'p_se0', nom: 'Göteborg', pays: 'Suède', flag: '🇸🇪' },
  { code: 'p_se1', nom: 'Stockholm', pays: 'Suède', flag: '🇸🇪' },
  { code: 'p_fi0', nom: 'Helsinki', pays: 'Finlande', flag: '🇫🇮' },
  { code: 'p_fi1', nom: 'Kotka', pays: 'Finlande', flag: '🇫🇮' },
  { code: 'p_fi2', nom: 'Rauma', pays: 'Finlande', flag: '🇫🇮' },
  { code: 'p_no0', nom: 'Oslo', pays: 'Norvège', flag: '🇳🇴' },
  { code: 'p_dk0', nom: 'Aarhus', pays: 'Danemark', flag: '🇩🇰' },
  { code: 'p_dk1', nom: 'Copenhague', pays: 'Danemark', flag: '🇩🇰' },
  { code: 'p_ie0', nom: 'Dublin', pays: 'Irlande', flag: '🇮🇪' },
  { code: 'p_ie1', nom: 'Cork', pays: 'Irlande', flag: '🇮🇪' },
  { code: 'p_gr0', nom: 'Le Pirée', pays: 'Grèce', flag: '🇬🇷' },
  { code: 'p_gr1', nom: 'Thessalonique', pays: 'Grèce', flag: '🇬🇷' },
  { code: 'p_tr0', nom: 'Istanbul (Ambarli)', pays: 'Turquie', flag: '🇹🇷' },
  { code: 'p_tr1', nom: 'Mersin', pays: 'Turquie', flag: '🇹🇷' },
  { code: 'p_tr2', nom: 'Izmir', pays: 'Turquie', flag: '🇹🇷' },
  { code: 'p_ro0', nom: 'Constanta', pays: 'Roumanie', flag: '🇷🇴' },
  { code: 'p_bg0', nom: 'Varna', pays: 'Bulgarie', flag: '🇧🇬' },
  { code: 'p_bg1', nom: 'Bourgas', pays: 'Bulgarie', flag: '🇧🇬' },
  { code: 'p_hr0', nom: 'Rijeka', pays: 'Croatie', flag: '🇭🇷' },
  { code: 'p_si0', nom: 'Koper', pays: 'Slovénie', flag: '🇸🇮' },
  { code: 'p_lv0', nom: 'Riga', pays: 'Lettonie', flag: '🇱🇻' },
  { code: 'p_lt0', nom: 'Klaipeda', pays: 'Lituanie', flag: '🇱🇹' },
  { code: 'p_ee0', nom: 'Tallinn', pays: 'Estonie', flag: '🇪🇪' },
  { code: 'p_za0', nom: 'Durban', pays: 'Afrique du Sud', flag: '🇿🇦' },
  { code: 'p_za1', nom: 'Le Cap', pays: 'Afrique du Sud', flag: '🇿🇦' },
  { code: 'p_za2', nom: 'Port Elizabeth', pays: 'Afrique du Sud', flag: '🇿🇦' },
  { code: 'p_al0', nom: 'Durrës', pays: 'Albanie', flag: '🇦🇱' },
  { code: 'p_dz0', nom: 'Alger', pays: 'Algérie', flag: '🇩🇿' },
  { code: 'p_dz1', nom: 'Oran', pays: 'Algérie', flag: '🇩🇿' },
  { code: 'p_ao0', nom: 'Luanda', pays: 'Angola', flag: '🇦🇴' },
  { code: 'p_ao1', nom: 'Lobito', pays: 'Angola', flag: '🇦🇴' },
  { code: 'p_sa0', nom: 'Djeddah', pays: 'Arabie saoudite', flag: '🇸🇦' },
  { code: 'p_sa1', nom: 'Dammam', pays: 'Arabie saoudite', flag: '🇸🇦' },
  { code: 'p_ar0', nom: 'Buenos Aires', pays: 'Argentine', flag: '🇦🇷' },
  { code: 'p_au0', nom: 'Sydney', pays: 'Australie', flag: '🇦🇺' },
  { code: 'p_au1', nom: 'Melbourne', pays: 'Australie', flag: '🇦🇺' },
  { code: 'p_au2', nom: 'Brisbane', pays: 'Australie', flag: '🇦🇺' },
  { code: 'p_bs0', nom: 'Nassau', pays: 'Bahamas', flag: '🇧🇸' },
  { code: 'p_bh0', nom: 'Khalifa Bin Salman', pays: 'Bahreïn', flag: '🇧🇭' },
  { code: 'p_bd0', nom: 'Chittagong', pays: 'Bangladesh', flag: '🇧🇩' },
  { code: 'p_mm0', nom: 'Yangon', pays: 'Birmanie', flag: '🇲🇲' },
  { code: 'p_ba0', nom: 'Ploče (via Croatie)', pays: 'Bosnie-Herzégovine', flag: '🇧🇦' },
  { code: 'p_bn0', nom: 'Muara', pays: 'Brunei', flag: '🇧🇳' },
  { code: 'p_br0', nom: 'Santos', pays: 'Brésil', flag: '🇧🇷' },
  { code: 'p_br1', nom: 'Paranaguá', pays: 'Brésil', flag: '🇧🇷' },
  { code: 'p_br2', nom: 'Itajaí', pays: 'Brésil', flag: '🇧🇷' },
  { code: 'p_bz0', nom: 'Belize City', pays: 'Bélize', flag: '🇧🇿' },
  { code: 'p_bj0', nom: 'Cotonou', pays: 'Bénin', flag: '🇧🇯' },
  { code: 'p_kh0', nom: 'Sihanoukville', pays: 'Cambodge', flag: '🇰🇭' },
  { code: 'p_cm0', nom: 'Douala', pays: 'Cameroun', flag: '🇨🇲' },
  { code: 'p_cm1', nom: 'Kribi', pays: 'Cameroun', flag: '🇨🇲' },
  { code: 'p_ca0', nom: 'Montréal', pays: 'Canada', flag: '🇨🇦' },
  { code: 'p_ca1', nom: 'Vancouver', pays: 'Canada', flag: '🇨🇦' },
  { code: 'p_ca2', nom: 'Halifax', pays: 'Canada', flag: '🇨🇦' },
  { code: 'p_cv0', nom: 'Praia', pays: 'Cap-Vert', flag: '🇨🇻' },
  { code: 'p_cl0', nom: 'San Antonio', pays: 'Chili', flag: '🇨🇱' },
  { code: 'p_cl1', nom: 'Valparaíso', pays: 'Chili', flag: '🇨🇱' },
  { code: 'p_cn0', nom: 'Shanghai', pays: 'Chine', flag: '🇨🇳' },
  { code: 'p_cn1', nom: 'Ningbo', pays: 'Chine', flag: '🇨🇳' },
  { code: 'p_cn2', nom: 'Shenzhen', pays: 'Chine', flag: '🇨🇳' },
  { code: 'p_cn3', nom: 'Qingdao', pays: 'Chine', flag: '🇨🇳' },
  { code: 'p_cn4', nom: 'Tianjin', pays: 'Chine', flag: '🇨🇳' },
  { code: 'p_cy0', nom: 'Limassol', pays: 'Chypre', flag: '🇨🇾' },
  { code: 'p_co0', nom: 'Carthagène', pays: 'Colombie', flag: '🇨🇴' },
  { code: 'p_co1', nom: 'Buenaventura', pays: 'Colombie', flag: '🇨🇴' },
  { code: 'p_km0', nom: 'Moroni', pays: 'Comores', flag: '🇰🇲' },
  { code: 'p_cg0', nom: 'Pointe-Noire', pays: 'Congo', flag: '🇨🇬' },
  { code: 'p_kr0', nom: 'Busan', pays: 'Corée du Sud', flag: '🇰🇷' },
  { code: 'p_kr1', nom: 'Incheon', pays: 'Corée du Sud', flag: '🇰🇷' },
  { code: 'p_cr0', nom: 'Puerto Limón', pays: 'Costa Rica', flag: '🇨🇷' },
  { code: 'p_cu0', nom: 'La Havane', pays: 'Cuba', flag: '🇨🇺' },
  { code: 'p_ci0', nom: 'Abidjan', pays: "Côte d'Ivoire", flag: '🇨🇮' },
  { code: 'p_dj0', nom: 'Djibouti', pays: 'Djibouti', flag: '🇩🇯' },
  { code: 'p_ga0', nom: 'Libreville', pays: 'Gabon', flag: '🇬🇦' },
  { code: 'p_gm0', nom: 'Banjul', pays: 'Gambie', flag: '🇬🇲' },
  { code: 'p_gh0', nom: 'Tema', pays: 'Ghana', flag: '🇬🇭' },
  { code: 'p_gt0', nom: 'Puerto Quetzal', pays: 'Guatemala', flag: '🇬🇹' },
  { code: 'p_gn0', nom: 'Conakry', pays: 'Guinée', flag: '🇬🇳' },
  { code: 'p_gq0', nom: 'Malabo', pays: 'Guinée équatoriale', flag: '🇬🇶' },
  { code: 'p_gq1', nom: 'Bata', pays: 'Guinée équatoriale', flag: '🇬🇶' },
  { code: 'p_gw0', nom: 'Bissau', pays: 'Guinée-Bissau', flag: '🇬🇼' },
  { code: 'p_gy0', nom: 'Georgetown', pays: 'Guyana', flag: '🇬🇾' },
  { code: 'p_ge0', nom: 'Poti', pays: 'Géorgie', flag: '🇬🇪' },
  { code: 'p_ht0', nom: 'Port-au-Prince', pays: 'Haïti', flag: '🇭🇹' },
  { code: 'p_hn0', nom: 'Puerto Cortés', pays: 'Honduras', flag: '🇭🇳' },
  { code: 'p_hk0', nom: 'Hong Kong', pays: 'Hong Kong', flag: '🇭🇰' },
  { code: 'p_in0', nom: 'Nhava Sheva (Mumbai)', pays: 'Inde', flag: '🇮🇳' },
  { code: 'p_in1', nom: 'Mundra', pays: 'Inde', flag: '🇮🇳' },
  { code: 'p_in2', nom: 'Chennai', pays: 'Inde', flag: '🇮🇳' },
  { code: 'p_id0', nom: 'Jakarta (Tanjung Priok)', pays: 'Indonésie', flag: '🇮🇩' },
  { code: 'p_id1', nom: 'Surabaya', pays: 'Indonésie', flag: '🇮🇩' },
  { code: 'p_iq0', nom: 'Umm Qasr', pays: 'Irak', flag: '🇮🇶' },
  { code: 'p_ir0', nom: 'Bandar Abbas', pays: 'Iran', flag: '🇮🇷' },
  { code: 'p_is0', nom: 'Reykjavik', pays: 'Islande', flag: '🇮🇸' },
  { code: 'p_il0', nom: 'Haïfa', pays: 'Israël', flag: '🇮🇱' },
  { code: 'p_il1', nom: 'Ashdod', pays: 'Israël', flag: '🇮🇱' },
  { code: 'p_jm0', nom: 'Kingston', pays: 'Jamaïque', flag: '🇯🇲' },
  { code: 'p_jp0', nom: 'Tokyo', pays: 'Japon', flag: '🇯🇵' },
  { code: 'p_jp1', nom: 'Yokohama', pays: 'Japon', flag: '🇯🇵' },
  { code: 'p_jp2', nom: 'Kobe', pays: 'Japon', flag: '🇯🇵' },
  { code: 'p_jo0', nom: 'Aqaba', pays: 'Jordanie', flag: '🇯🇴' },
  { code: 'p_ke0', nom: 'Mombasa', pays: 'Kenya', flag: '🇰🇪' },
  { code: 'p_kw0', nom: 'Shuwaikh', pays: 'Koweït', flag: '🇰🇼' },
  { code: 'p_lb0', nom: 'Beyrouth', pays: 'Liban', flag: '🇱🇧' },
  { code: 'p_lr0', nom: 'Monrovia', pays: 'Liberia', flag: '🇱🇷' },
  { code: 'p_ly0', nom: 'Tripoli', pays: 'Libye', flag: '🇱🇾' },
  { code: 'p_ly1', nom: 'Misrata', pays: 'Libye', flag: '🇱🇾' },
  { code: 'p_ly2', nom: 'Benghazi', pays: 'Libye', flag: '🇱🇾' },
  { code: 'p_mg0', nom: 'Tamatave', pays: 'Madagascar', flag: '🇲🇬' },
  { code: 'p_my0', nom: 'Port Klang', pays: 'Malaisie', flag: '🇲🇾' },
  { code: 'p_my1', nom: 'Tanjung Pelepas', pays: 'Malaisie', flag: '🇲🇾' },
  { code: 'p_mv0', nom: 'Malé', pays: 'Maldives', flag: '🇲🇻' },
  { code: 'p_mt0', nom: 'Marsaxlokk', pays: 'Malte', flag: '🇲🇹' },
  { code: 'p_ma0', nom: 'Casablanca', pays: 'Maroc', flag: '🇲🇦' },
  { code: 'p_ma1', nom: 'Tanger Med', pays: 'Maroc', flag: '🇲🇦' },
  { code: 'p_ma2', nom: 'Agadir', pays: 'Maroc', flag: '🇲🇦' },
  { code: 'p_mr0', nom: 'Nouakchott', pays: 'Mauritanie', flag: '🇲🇷' },
  { code: 'p_mx0', nom: 'Veracruz', pays: 'Mexique', flag: '🇲🇽' },
  { code: 'p_mx1', nom: 'Manzanillo', pays: 'Mexique', flag: '🇲🇽' },
  { code: 'p_me0', nom: 'Bar', pays: 'Monténégro', flag: '🇲🇪' },
  { code: 'p_mz0', nom: 'Maputo', pays: 'Mozambique', flag: '🇲🇿' },
  { code: 'p_mz1', nom: 'Beira', pays: 'Mozambique', flag: '🇲🇿' },
  { code: 'p_na0', nom: 'Walvis Bay', pays: 'Namibie', flag: '🇳🇦' },
  { code: 'p_ni0', nom: 'Corinto', pays: 'Nicaragua', flag: '🇳🇮' },
  { code: 'p_ng0', nom: 'Lagos (Apapa)', pays: 'Nigeria', flag: '🇳🇬' },
  { code: 'p_ng1', nom: 'Onne', pays: 'Nigeria', flag: '🇳🇬' },
  { code: 'p_nz0', nom: 'Auckland', pays: 'Nouvelle-Zélande', flag: '🇳🇿' },
  { code: 'p_nz1', nom: 'Tauranga', pays: 'Nouvelle-Zélande', flag: '🇳🇿' },
  { code: 'p_om0', nom: 'Sohar', pays: 'Oman', flag: '🇴🇲' },
  { code: 'p_om1', nom: 'Salalah', pays: 'Oman', flag: '🇴🇲' },
  { code: 'p_pk0', nom: 'Karachi', pays: 'Pakistan', flag: '🇵🇰' },
  { code: 'p_pa0', nom: 'Balboa', pays: 'Panama', flag: '🇵🇦' },
  { code: 'p_pa1', nom: 'Colón', pays: 'Panama', flag: '🇵🇦' },
  { code: 'p_pg0', nom: 'Port Moresby', pays: 'Papouasie-Nlle-Guinée', flag: '🇵🇬' },
  { code: 'p_ph0', nom: 'Manille', pays: 'Philippines', flag: '🇵🇭' },
  { code: 'p_ph1', nom: 'Cebu', pays: 'Philippines', flag: '🇵🇭' },
  { code: 'p_pe0', nom: 'Callao', pays: 'Pérou', flag: '🇵🇪' },
  { code: 'p_qa0', nom: 'Hamad (Doha)', pays: 'Qatar', flag: '🇶🇦' },
  { code: 'p_cd0', nom: 'Matadi', pays: 'RD Congo', flag: '🇨🇩' },
  { code: 'p_ru0', nom: 'Saint-Pétersbourg', pays: 'Russie', flag: '🇷🇺' },
  { code: 'p_ru1', nom: 'Novorossiisk', pays: 'Russie', flag: '🇷🇺' },
  { code: 'p_ru2', nom: 'Vladivostok', pays: 'Russie', flag: '🇷🇺' },
  { code: 'p_do0', nom: 'Caucedo', pays: 'Rép. dominicaine', flag: '🇩🇴' },
  { code: 'p_sv0', nom: 'Acajutla', pays: 'Salvador', flag: '🇸🇻' },
  { code: 'p_sc0', nom: 'Victoria', pays: 'Seychelles', flag: '🇸🇨' },
  { code: 'p_sl0', nom: 'Freetown', pays: 'Sierra Leone', flag: '🇸🇱' },
  { code: 'p_sg0', nom: 'Singapour', pays: 'Singapour', flag: '🇸🇬' },
  { code: 'p_so0', nom: 'Mogadiscio', pays: 'Somalie', flag: '🇸🇴' },
  { code: 'p_sd0', nom: 'Port-Soudan', pays: 'Soudan', flag: '🇸🇩' },
  { code: 'p_lk0', nom: 'Colombo', pays: 'Sri Lanka', flag: '🇱🇰' },
  { code: 'p_sr0', nom: 'Paramaribo', pays: 'Suriname', flag: '🇸🇷' },
  { code: 'p_sy0', nom: 'Lattaquié', pays: 'Syrie', flag: '🇸🇾' },
  { code: 'p_sn0', nom: 'Dakar', pays: 'Sénégal', flag: '🇸🇳' },
  { code: 'p_tz0', nom: 'Dar es Salaam', pays: 'Tanzanie', flag: '🇹🇿' },
  { code: 'p_tw0', nom: 'Kaohsiung', pays: 'Taïwan', flag: '🇹🇼' },
  { code: 'p_tw1', nom: 'Keelung', pays: 'Taïwan', flag: '🇹🇼' },
  { code: 'p_th0', nom: 'Laem Chabang (Bangkok)', pays: 'Thaïlande', flag: '🇹🇭' },
  { code: 'p_tg0', nom: 'Lomé', pays: 'Togo', flag: '🇹🇬' },
  { code: 'p_tt0', nom: "Port d'Espagne", pays: 'Trinité-et-Tobago', flag: '🇹🇹' },
  { code: 'p_tn0', nom: 'Radès (Tunis)', pays: 'Tunisie', flag: '🇹🇳' },
  { code: 'p_tn1', nom: 'Sfax', pays: 'Tunisie', flag: '🇹🇳' },
  { code: 'p_ua0', nom: 'Odessa', pays: 'Ukraine', flag: '🇺🇦' },
  { code: 'p_uy0', nom: 'Montevideo', pays: 'Uruguay', flag: '🇺🇾' },
  { code: 'p_ve0', nom: 'La Guaira', pays: 'Venezuela', flag: '🇻🇪' },
  { code: 'p_ve1', nom: 'Puerto Cabello', pays: 'Venezuela', flag: '🇻🇪' },
  { code: 'p_vn0', nom: 'Hô Chi Minh (Cat Lai)', pays: 'Vietnam', flag: '🇻🇳' },
  { code: 'p_vn1', nom: 'Haïphong', pays: 'Vietnam', flag: '🇻🇳' },
  { code: 'p_ye0', nom: 'Aden', pays: 'Yémen', flag: '🇾🇪' },
  { code: 'p_eg0', nom: 'Alexandrie', pays: 'Égypte', flag: '🇪🇬' },
  { code: 'p_eg1', nom: 'Port-Saïd', pays: 'Égypte', flag: '🇪🇬' },
  { code: 'p_eg2', nom: 'Damiette', pays: 'Égypte', flag: '🇪🇬' },
  { code: 'p_ae0', nom: 'Jebel Ali (Dubaï)', pays: 'Émirats arabes unis', flag: '🇦🇪' },
  { code: 'p_ae1', nom: 'Abou Dabi', pays: 'Émirats arabes unis', flag: '🇦🇪' },
  { code: 'p_ec0', nom: 'Guayaquil', pays: 'Équateur', flag: '🇪🇨' },
  { code: 'p_er0', nom: 'Massawa', pays: 'Érythrée', flag: '🇪🇷' },
  { code: 'p_us0', nom: 'New York', pays: 'États-Unis', flag: '🇺🇸' },
  { code: 'p_us1', nom: 'Savannah', pays: 'États-Unis', flag: '🇺🇸' },
  { code: 'p_us2', nom: 'Los Angeles', pays: 'États-Unis', flag: '🇺🇸' },
  { code: 'p_us3', nom: 'Houston', pays: 'États-Unis', flag: '🇺🇸' },
  { code: 'p_us4', nom: 'Miami', pays: 'États-Unis', flag: '🇺🇸' },
  { code: 'p_mu0', nom: 'Port-Louis', pays: 'Île Maurice', flag: '🇲🇺' },
];


/* PORTS d'abord (les plus gros/classiques en tête), pays ensuite (14/09 Ethan) */
const PROV_SUGG = [...PORTS_PROV, ...PAYS_PROV];

/* suggestions destination : chaque PAYS et chaque PORT sont pickables séparément */
const PORTS_DEST_EXTRA = [
  { code: 'MA', port: 'Tanger Med' },
  { code: 'DZ', port: 'Oran' },
  { code: 'TN', port: 'Sfax' },
  { code: 'ES', port: 'Barcelone' },
  { code: 'ES', port: 'Algésiras' },
  { code: 'TR', port: 'Mersin' },
  { code: 'TR', port: 'Izmir' },
  { code: 'EG', port: 'Port-Saïd' },
  { code: 'EG', port: 'Damiette' },
  { code: 'IN', port: 'Mundra' },
];
const DEST_PORTS = [
  ...PAYS.map(p => ({ id: 'p_' + p.code, code: p.code, nom: p.port, flag: p.flag, pays: p.nom })),
  ...PORTS_DEST_EXTRA.map((e, i) => {
    const p = PAYS.find(x => x.code === e.code);
    return { id: 'x_' + i, code: e.code, nom: e.port, flag: p.flag, pays: p.nom };
  }),
];

const DEST_FRET = 'support@prodi.com';   // la boîte de Zouhir (zouhir@ n'existe pas)
const CC_INTERNE = ['julien@prodi.com', 'client@prodi.com', 've@prodi.com'];

/* ── Demandes passées (fictives) ── */
const DEMANDES = [
  {
    ref: 'FR-2601', pays: 'MA', client: 'PAPETERIE ATLAS', provenance: 'France',
    nbCont: 1, taille: '20', marchandise: 'Bobines',
    incoterm: 'CFR', date: '2026-08-12T09:14:00', cibles: ['translog', 'atlas', 'seafret', 'mtl', 'globalwave'],
  },
  {
    ref: 'FR-2602', pays: 'TR', client: 'KAGIT LTD', provenance: 'France',
    nbCont: 2, taille: '20', marchandise: 'Bobines',
    incoterm: 'CFR', date: '2026-08-19T15:40:00', cibles: ['mtl', 'globalwave'],
  },
  {
    ref: 'FR-2603', pays: 'SN', client: 'SOPACO SARL', provenance: 'France',
    nbCont: 1, taille: '20', marchandise: 'Bobines',
    incoterm: 'CFR', date: '2026-08-25T10:05:00', cibles: ['seafret', 'capouest', 'mtl', 'globalwave'],
  },
  {
    ref: 'FR-2604', pays: 'MA', client: 'PAPETERIE ATLAS', provenance: 'France',
    nbCont: 2, taille: '20', marchandise: 'Bobines',
    incoterm: 'CFR', date: '2026-08-31T11:30:00', cibles: ['translog', 'atlas', 'seafret', 'mtl', 'globalwave'],
  },
];

/* ── Réponses reçues (fictives) — prix en € ── */
const REPONSES = [
  /* FR-2601 · Maroc · 12/08 */
  { demande: 'FR-2601', transporteur: 'translog',  prix: 870,  unite: '20', incoterm: 'CFR', transit: '4-5 j',  recu: '2026-08-12T11:02:00',
    texte: "Bonjour Ethan,\n\nPour Casablanca on vous fait 870 € le 20' CFR, transit 4/5 jours, départ Marseille chaque jeudi.\nValidité 15 jours.\n\nCordialement,\nKarim" },
  { demande: 'FR-2601', transporteur: 'atlas',     prix: 905,  unite: '20', incoterm: 'CFR', transit: '5 j',    recu: '2026-08-12T14:37:00',
    texte: "Bonjour,\n\nNotre meilleure offre : 905 EUR / TC20 CFR Casa, transit 5 jours.\n\nBien à vous,\nSofia" },
  { demande: 'FR-2601', transporteur: 'seafret',   prix: 890,  unite: '20', incoterm: 'CFR', transit: '6 j',    recu: '2026-08-13T09:20:00',
    texte: "Bonjour,\n\n890 € le container 20 pieds CFR Casablanca, départ Le Havre, transit 6 jours.\n\nMarc" },
  { demande: 'FR-2601', transporteur: 'mtl',       prix: 980,  unite: '20', incoterm: 'CFR', transit: '5 j',    recu: '2026-08-14T16:55:00',
    texte: "Hello,\n\nOn est à 980 € TC20 CFR Casa en ce moment, marché tendu.\n\nDavid" },
  /* globalwave n'a pas répondu à FR-2601 */

  /* FR-2602 · Turquie · 19/08 */
  { demande: 'FR-2602', transporteur: 'mtl',       prix: 1040, unite: '20', incoterm: 'CFR', transit: '9 j',    recu: '2026-08-20T10:12:00',
    texte: "Bonjour Ethan,\n\nAmbarlı : 1 040 € par 20' CFR, transit 9 jours via Le Pirée.\n\nDavid" },
  { demande: 'FR-2602', transporteur: 'globalwave', prix: null, unite: null, incoterm: null,  transit: null,     recu: '2026-08-21T09:00:00', flagged: true,
    texte: "Bonjour,\n\nÇa dépend de la semaine de départ, comptez entre 45 et 52 la tonne selon le navire. Rappelez-moi pour caler ça.\n\nYusuf" },

  /* FR-2603 · Sénégal · 25/08 */
  { demande: 'FR-2603', transporteur: 'capouest',  prix: 1390, unite: '20', incoterm: 'CFR', transit: '11 j',   recu: '2026-08-25T13:44:00',
    texte: "Bonjour,\n\nDakar : 1 390 € le TC20 CFR, transit 11 jours, départ Anvers.\n\nAwa" },
  { demande: 'FR-2603', transporteur: 'seafret',   prix: 1445, unite: '20', incoterm: 'CFR', transit: '10 j',   recu: '2026-08-26T08:15:00',
    texte: "Bonjour,\n\n1 445 € / 20' CFR Dakar, transit 10 jours.\n\nMarc" },
  { demande: 'FR-2603', transporteur: 'mtl',       prix: 1520, unite: '20', incoterm: 'CFR', transit: '12 j',   recu: '2026-08-27T17:30:00',
    texte: "Bonjour,\n\nOn est à 1 520 € le 20 pieds sur Dakar CFR.\n\nDavid" },
  /* globalwave n'a pas répondu à FR-2603 */

  /* FR-2604 · Maroc · 31/08 */
  { demande: 'FR-2604', transporteur: 'translog',  prix: 860,  unite: '20', incoterm: 'CFR', transit: '4-5 j',  recu: '2026-08-31T14:20:00',
    texte: "Bonjour Ethan,\n\nToujours ok sur Casa : 860 € le 20' CFR pour 2 boîtes, transit 4/5 jours.\n\nKarim" },
  { demande: 'FR-2604', transporteur: 'seafret',   prix: 875,  unite: '20', incoterm: 'CFR', transit: '6 j',    recu: '2026-09-01T09:48:00',
    texte: "Bonjour,\n\n875 € par container CFR Casablanca sur cette période.\n\nMarc" },
  { demande: 'FR-2604', transporteur: 'atlas',     prix: 915,  unite: '20', incoterm: 'CFR', transit: '5 j',    recu: '2026-09-01T18:05:00',
    texte: "Bonjour,\n\n915 EUR / TC20 CFR Casa. Possibilité -10 € si 4 boîtes ou plus.\n\nSofia" },

  /* ── historique plus ancien pour nourrir les courbes ── */
  { demande: 'FR-2588', transporteur: 'translog',  prix: 910,  unite: '20', incoterm: 'CFR', transit: '5 j',  recu: '2026-06-18T10:00:00', pays: 'MA',
    texte: "910 € le 20' CFR Casablanca.\n\nKarim" },
  { demande: 'FR-2588', transporteur: 'atlas',     prix: 940,  unite: '20', incoterm: 'CFR', transit: '5 j',  recu: '2026-06-18T15:00:00', pays: 'MA',
    texte: "940 EUR / TC20 CFR Casa.\n\nSofia" },
  { demande: 'FR-2588', transporteur: 'mtl',       prix: 1010, unite: '20', incoterm: 'CFR', transit: '5 j',  recu: '2026-06-19T11:00:00', pays: 'MA',
    texte: "1 010 € TC20 CFR Casa.\n\nDavid" },
  { demande: 'FR-2592', transporteur: 'translog',  prix: 895,  unite: '20', incoterm: 'CFR', transit: '5 j',  recu: '2026-07-10T09:30:00', pays: 'MA',
    texte: "895 € le 20' CFR Casa.\n\nKarim" },
  { demande: 'FR-2592', transporteur: 'seafret',   prix: 900,  unite: '20', incoterm: 'CFR', transit: '6 j',  recu: '2026-07-10T14:10:00', pays: 'MA',
    texte: "900 € / 20' CFR Casablanca.\n\nMarc" },
  { demande: 'FR-2592', transporteur: 'atlas',     prix: 925,  unite: '20', incoterm: 'CFR', transit: '5 j',  recu: '2026-07-11T10:45:00', pays: 'MA',
    texte: "925 EUR TC20 CFR Casa.\n\nSofia" },
  { demande: 'FR-2595', transporteur: 'capouest',  prix: 1440, unite: '20', incoterm: 'CFR', transit: '11 j', recu: '2026-07-22T11:00:00', pays: 'SN',
    texte: "1 440 € TC20 CFR Dakar.\n\nAwa" },
  { demande: 'FR-2595', transporteur: 'seafret',   prix: 1480, unite: '20', incoterm: 'CFR', transit: '10 j', recu: '2026-07-22T16:20:00', pays: 'SN',
    texte: "1 480 € / 20' CFR Dakar.\n\nMarc" },
  { demande: 'FR-2597', transporteur: 'mtl',       prix: 1085, unite: '20', incoterm: 'CFR', transit: '9 j',  recu: '2026-07-28T10:00:00', pays: 'TR',
    texte: "1 085 € TC20 CFR Ambarlı.\n\nDavid" },
  { demande: 'FR-2597', transporteur: 'globalwave', prix: 1120, unite: '20', incoterm: 'CFR', transit: '10 j', recu: '2026-07-28T18:40:00', pays: 'TR',
    texte: "1 120 € le 20 pieds CFR Istanbul.\n\nYusuf" },
];

/* pays des vieilles demandes hors DEMANDES (pour l'historique) */
const DEMANDES_ARCHIVE = {
  'FR-2588': { pays: 'MA', date: '2026-06-18T08:30:00' },
  'FR-2592': { pays: 'MA', date: '2026-07-10T08:00:00' },
  'FR-2595': { pays: 'SN', date: '2026-07-22T09:15:00' },
  'FR-2597': { pays: 'TR', date: '2026-07-28T08:45:00' },
};
